1. Write a code to reverse a string.

In [ ]:
# by using scilicing function
string="qwertyui"
string[::-1]

'iuytrewq'

In [ ]:
# by using reverse function of list
l=list(string)
l.reverse()
rs="".join(l)
rs

'iuytrewq'

In [ ]:
# by using for loop
s=""
for i in string:
  s=i+s
s

'iuytrewq'

In [ ]:
# by using one line for loop
rs2 = "".join([string[i] for i in range(len(string)-1, -1, -1)])
rs2

'iuytrewq'

2. Write a code to count the number of vowels in a string.

In [ ]:
# by using for loop
string="aeiouwqvcbhnaeiou"
count=0
for i in string.lower():
  if i in ["a","i","e","o","u"]:
    count+=1
print("Count of vowels in string - ",count)

Count of vowels in string -  10

In [ ]:
# one line code

c=len([i for i in string.lower() if i in ["a","i","e","o","u"]])
c

10

3. Write a code to check if a given string is a palindrome or not.

In [ ]:
# by using silicing function
string="rammar"
rs=string[::-1].lower()
if rs==string.lower():
  print("given string is palindrome")

given string is palindrome

In [ ]:
# by taking input from user
string=input("enter a string to check is a palindrome :- ")
rs=string[::-1].lower()
if rs==string.lower():
  print("given string is palindrome")
else:
  print("given string is not palindrome")

enter a string to check is a palindrome :- dnfnoi
given string is not palindrome

4. Write a code to check if two given strings are anagrams of each other.

Two strings are said to be anagram if we can form one string by arranging the characters of another string. For example, Race and Care. Here, we can form Race by arranging the characters of Care.

In [ ]:
# 1st step is check for length should be same and convert both strings into lower or upper case
# 2nd step is take alpebatical order of each string and compare it if it same then it is a anagrams of each other
s1="Race"
s2="care"
if len(s1)==len(s2):
  s1=s1.lower()
  s2=s2.lower()
  if sorted(s1)==sorted(s2):
    print("both strings are anagrams of each other")
  else:
    print("both strings are not anagrams of each other")
else:
  print("both strings are not anagrams of each other ")

both strings are anagrams of each other

5. Write a code to find all occurrences of a given substring within another string.

In [ ]:
string="amdferamcrfeam"
sub_string="am"
str_len=len(string)
sub_str_len=len(sub_string)
occ=[]
for i in range(str_len):
  if string[i:i+sub_str_len] == sub_string:
    occ.append(i)
print("main string is - ",string)
print("sub string is - ",sub_string)
print("The starting indices of the occurrences of sub string in the string are - ",occ)

main string is -  amdferamcrfeam
sub string is -  am
The starting indices of the occurrences of sub string in the string are -  [0, 6, 12]

6. Write a code to perform basic string compression using the counts of repeated characters.

In [ ]:
def string_compression(s):
    result = ""
    if not s:
        return result
    char_count = 1  # Initialize character count to 1
    for i in range(1, len(s)):
        if s[i] == s[i - 1]:
            char_count += 1
        else:
            result += s[i - 1] + str(char_count)
            char_count = 1
    result += s[-1] + str(char_count)
    return result

string="aaasserterrrdddggf"
print("the string compression of counts of repeated characters for this string - ",string)
print("string compression is - ",string_compression(string))

the string compression of counts of repeated characters for this string -  aaasserterrrdddggf
string compression is -  a3s2e1r1t1e1r3d3g2f1

7. Write a code to determine if a string has all unique characters.

In [3]:
string="abcdefghijklmnopqrst"
c=True
for i in range(len(string)):
  for j in range(i+1,len(string)):
    if (string[i]==string[j]):
      c=False

if c:
  print(" string has all unique characters")
else:
  print(" string has not  all unique characters")

 string has all unique characters

8. Write a code to convert a given string to uppercase or lowercase.

In [4]:
string="abCDseHJK"
print("uppercase string is - ",string.upper())
print("lowercase string is - ",string.lower())

uppercase string is -  ABCDSEHJK
lowercase string is -  abcdsehjk

9. Write a code to count the number of words in a string.

In [5]:
string="I love My India"
l=string.split(" ")
print("count of words in string is - ",len(l))

count of words in string is -  4

10. Write a code to concatenate two strings without using the + operator.

In [11]:
string1="Jai"
string2="ShreeRam"
print("concateated string is  by using join method- ","".join([string1,string2]))

print(f"concateated string is  by using f-string method - {string1}{string2} ")

concateated string is  by using join method-  JaiShreeRam
concateated string is  by using f-string method - JaiShreeRam

11. Write a code to remove all occurrences of a specific element from a list.

In [13]:
l=[1,2,3,2,4,5,6,2,3,4,2]
r=2 # remove all occurrences of 2 decalar as r
for i in l:
  if i==r:
    l.remove(r)
l

[1, 3, 4, 5, 6, 3, 4]

12. Implement a code to find the second largest number in a given list of integers.

In [16]:
l=[23,45,123,65,43,76,98]
l.sort(reverse=True)
print("second largest number is  - ",l[1])

second largest number is  -  98

13. Create a code to count the occurrences of each element in a list and return a dictionary with elements as keys and their counts as values.

In [20]:
l=["ram","sham","ajay","shiv","ram","shiv","sham","ram"]
d={} # create a empty dictionary for store keys and value
s=set(l)
for i in s:
  count=0
  for j in range(len(l)):
    if i==l[j]:
      count+=1
  d1={i:count}
  d.update(d1)

d

{'shiv': 2, 'sham': 2, 'ajay': 1, 'ram': 3}

14. Write a code to reverse a list in-place without using any built-in reverse functions

In [27]:
l=[23,45,123,65,43,76,98]
l1=[]
for i in l:
  l1.insert(0,i)

l1

[98, 76, 43, 65, 123, 45, 23]

15. Implement a code to find and remove duplicates from a list while preserving the original order of elements.

In [34]:
l=[1,2,3,2,1,4,6,5,3,2,4,6,1]
res = []
for i in l:
  if i not in res:
    res.append(i)


res

[1, 2, 3, 4, 6, 5]

16. Create a code to check if a given list is sorted (either in ascending or descending order) or not.

In [81]:
l=[11,10,9,8,7]
a_s=l.copy()
d_s=l.copy()
for i in range(len(l)):
  for j in range(i+1,len(l)):
    if a_s[i] >= a_s[j]:
            a_s[i], a_s[j] = a_s[j],a_s[i]
    elif d_s[i] <= d_s[j]:
            d_s[i], d_s[j] = d_s[j],d_s[i]

if l==a_s:
  print("ascending alrady")
elif l==d_s:
  print("descending alrady")
else:
  print("not sorted")

descending alrady

17. Write a code to merge two sorted lists into a single sorted list.

In [82]:
l1=[23,54,67,21,27,56]
l2=[45,76,14,25,29,30,55]
l1.sort()
l2.sort()
l=l1+l2
l.sort()
l

[14, 21, 23, 25, 27, 29, 30, 45, 54, 55, 56, 67, 76]

18. Implement a code to find the intersection of two given lists.

In [83]:

l1 = [1, 2, 3, 4, 5]
l2 = [3, 5, 6, 7, 8]

intersection = list(set(l1) & set(l2))
intersection

[3, 5]

19. Create a code to find the union of two lists without duplicates.

In [86]:
l1 = [1, 2, 3, 4, 5]
l2 = [3, 5, 6, 7, 8,8]

union = list(set(l1) | set(l2))
union

[1, 2, 3, 4, 5, 6, 7, 8]

20. Write a code to shuffle a given list randomly without using any built-in shuffle functions.

In [87]:
l=[23,54,78,90,33,65,72,12]
for i in range(len(l)):
  for j in range(i+2,len(l)):
    l[i],l[j]=l[j],l[i]
l

[12, 72, 65, 33, 90, 78, 23, 54]

21. Write a code that takes two tuples as input and returns a new tuple containing elements that are common to both input tuples.

In [90]:

tuple1 = tuple(input("enter element for tuple1 (ex - enter in this way 234565) - "))
tuple2 = tuple(input("enter element for tuple2 (ex - enter in this way 234565)- "))


common_tuple = tuple(set(tuple1) & set(tuple2))
common_tuple

enter element for tuple1 (ex - enter in this way 234565) - 12345
enter element for tuple2 (ex - enter in this way 234565)- 453

('4', '3', '5')

22. Create a code that prompts the user to enter two sets of integers separated by commas. Then, print the intersection of these two sets.

In [ ]:
set1_input = input("Enter the first set of integers separated by commas: ")
set2_input = input("Enter the second set of integers separated by commas: ")

set1 = set(map(int, set1_input.split(',')))
set2 = set(map(int, set2_input.split(',')))

intersection_set = set1.intersection(set2)

print("Intersection of the two sets:", intersection_set)

23. Write a code to concatenate two tuples. The function should take two tuples as input and return a new tuple containing elements from both input tuples.

In [91]:
tuple1 = tuple(input("enter element for tuple1 (ex - enter in this way 234565) - "))
tuple2 = tuple(input("enter element for tuple2 (ex - enter in this way 234565)- "))

result =  tuple1 + tuple2
print(result)

enter element for tuple1 (ex - enter in this way 234565) - 12345
enter element for tuple2 (ex - enter in this way 234565)- 23456
('1', '2', '3', '4', '5', '2', '3', '4', '5', '6')


24. Develop a code that prompts the user to input two sets of strings. Then, print the elements that are present in the first set but not in the second set.

In [92]:
set1_input = input("Enter the first set of strings separated by commas: ")
set2_input = input("Enter the second set of strings separated by commas: ")

set1 = set(set1_input.split(','))
set2 = set(set2_input.split(','))

difference_set = set1.difference(set2)

print("Elements in the first set but not in the second set:", difference_set)

Enter the first set of strings separated by commas: 2,3,4,5
Enter the second set of strings separated by commas: 4,5,6,7
Elements in the first set but not in the second set: {'3', '2'}

25. Create a code that takes a tuple and two integers as input. The function should return a new tuple containing elements from the original tuple within the specified range of indices.

In [97]:
t=input("enter tuple values in two digit integers by comma sepratre -  ")
tuple1=tuple([int(x) for x in t.split(",")])
start_index = 1
end_index = 4
result_tuple = tuple1[start_index:end_index]
print(result_tuple)

enter tuple values in two digit integers by comma sepratre -  34,56,76,54,34,32,4
(56, 76, 54)

26. Write a code that prompts the user to input two sets of characters. Then, print the union of these two sets.

In [98]:
set1_input = input("Enter the first set of characters separated by commas: ")
set2_input = input("Enter the second set of characters separated by commas: ")

set1 = set(set1_input.split(','))
set2 = set(set2_input.split(','))

union_set = set1.union(set2)

print("Union of the two sets:", union_set)

Enter the first set of characters separated by commas: 1,2,3,4,5,6
Enter the second set of characters separated by commas: 2,3,4,5,6,7
Union of the two sets: {'3', '4', '7', '1', '6', '5', '2'}

27. Develop a code that takes a tuple of integers as input. The function should return the maximum and minimum values from the tuple using tuple unpacking.

In [99]:
t=input("enter tuple values in  integers by comma sepratre -  ")
tuple1=tuple([int(x) for x in t.split(",")])
min_value, max_value = min(tuple1), max(tuple1)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

enter tuple values in  integers by comma sepratre -  23,45,67,54,32,45,89,1
Minimum value: 1
Maximum value: 89

28. Create a code that defines two sets of integers. Then, print the union, intersection, and difference of these two sets.

In [100]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 5, 6, 7, 8}

# Union of sets
union_set = set1 | set2
print("Union:", union_set)

# Intersection of sets
intersection_set = set1 & set2
print("Intersection:", intersection_set)

# Difference of sets (set1 - set2)
difference_set1 = set1 - set2
print("Difference (set1 - set2):", difference_set1)

# Difference of sets (set2 - set1)
difference_set2 = set2 - set1
print("Difference (set2 - set1):", difference_set2)

Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {3, 5}
Difference (set1 - set2): {1, 2, 4}
Difference (set2 - set1): {8, 6, 7}

29. Write a code that takes a tuple and an element as input. The function should return the count of occurrences of the given element in the tuple.

In [101]:
t=input("enter tuple values in  integers by comma sepratre -  ")
tuple1=tuple([int(x) for x in t.split(",")])
element_to_count = 2
count = 0
for i in tuple1:
  if i==element_to_count:
    count+=1
print(f"The element {element_to_count} appears {count} times in the tuple.")

enter tuple values in  integers by comma sepratre -  1,2,3,4,5,2,4,3,2
The element 2 appears 3 times in the tuple.

30. Develop a code that prompts the user to input two sets of strings. Then, print the symmetric difference of these two sets.

In [102]:
set1_input = input("Enter the first set of strings separated by commas: ")
set2_input = input("Enter the second set of strings separated by commas: ")

set1 = set(set1_input.split(','))
set2 = set(set2_input.split(','))

symmetric_difference_set = set1.symmetric_difference(set2)

print("Symmetric Difference of the two sets:", symmetric_difference_set)

Enter the first set of strings separated by commas: 1,2,3,4,5
Enter the second set of strings separated by commas: 3,4,5,6,7
Symmetric Difference of the two sets: {'7', '1', '2', '6'}

31. Write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list.

In [103]:
l=input("enter a words in list by comma seprates - ").split(",")
d={} # create a empty dictionary for store keys and value
s=set(l)
for i in s:
  count=0
  for j in range(len(l)):
    if i==l[j]:
      count+=1
  d1={i:count}
  d.update(d1)

d

enter a words in list by comma seprates - ram,sham,ram,sham,ram,jai,veer

{'jai': 1, 'sham': 2, 'veer': 1, 'ram': 3}

32. Write a code that takes two dictionaries as input and merges them into a single dictionary. If there are common keys, the values should be added together.

In [106]:
dict1 = {'a': 10, 'b': 35, 'c': 30}
dict2 = {'b': 15, 'd': 40,'c':40}
merged_dict = dict1.copy()
for key, value in dict2.items():
    if key in merged_dict:
      merged_dict[key] += value
    else:
      merged_dict[key] = value
print(merged_dict)

{'a': 10, 'b': 50, 'c': 70, 'd': 40}

33. Write a code to access a value in a nested dictionary. The function should take the dictionary and a list of keys as input, and return the corresponding value. If any of the keys do not exist in the dictionary, the function should return None.

In [114]:
people = {1: {'name': 'John', 'age': '27', 'sex': 'Male'},
          2: {'name': 'Marie', 'age': '22', 'sex': 'Female'}}
keys = [2, 'name']
for key in keys:
    if key in people:
      people = people[key]
      print(people)
    else:
      print(None)

{'name': 'Marie', 'age': '22', 'sex': 'Female'}
Marie

34. Write a code that takes a dictionary as input and returns a sorted version of it based on the values. You can choose whether to sort in ascending or descending order.

In [115]:
my_dict = {'apple': 5, 'banana': 2, 'cherry': 8}

# Sort in ascending order based on values
sorted_dict_asc = dict(sorted(my_dict.items(), key=lambda item: item[1]))
print("Ascending order:", sorted_dict_asc)

# Sort in descending order based on values
sorted_dict_desc = dict(sorted(my_dict.items(), key=lambda item: item[1], reverse=True))
print("Descending order:", sorted_dict_desc)

Ascending order: {'banana': 2, 'apple': 5, 'cherry': 8}
Descending order: {'cherry': 8, 'apple': 5, 'banana': 2}

35. Write a code that inverts a dictionary, swapping keys and values. Ensure that the inverted dictionary correctly handles cases where multiple keys have the same value by storing the keys as a list in the inverted dictionary

In [116]:
my_dict = {'a': 1, 'b': 2, 'c': 1, 'd': 3}

inverted_dict = {}
for key, value in my_dict.items():
  if value not in inverted_dict:
    inverted_dict[value] = [key]
  else:
    inverted_dict[value].append(key)

print(inverted_dict)

{1: ['a', 'c'], 2: ['b'], 3: ['d']}